### ISSUE TITLE
Folks, I have a hard time using MINOTAUR. Can we add a few examples of basic usage?

### ISSUE THREAD

**Issue by grunwald** [NESCent/MINOTAUR#1]
Can we add a few examples of basic usage? MINOTAUR looks daunting without guidance.

**Comment by DrK-Lo** [comment]
Here is a basic example of calculating the multivariate summary stats:

dfv <- data.frame(var1, var2, var3)
The rows in the dataframe are SNPs or loci.
The three variables might be test statistics from associations between genotypes and three correlated phenotypes, between genotypes and three correlated environments, or from different types of tests (i.e. FST, GWAS, genetic-environment association).  Also see the email I forwarded you from Sam Yeaman for another type of problem.

To calculate Mahalonobis distance 
The first entry is the dataframe and the second is the rows in that dataframe you would like to include in the calculation:
>Mahalanobis(dfv, 1:3)

To calculate kernel density 
The first entry is the dataframe and the second is the rows in that dataframe you would like to include in the calculation:
>KernelDensityML(dfv, 1:3)

Both functions return a list.  The first item in the list is the summary statistic, larger values indicate more "outlierly" loci.  The second list item is the rank, and the third is the rank divided by the total number of observations (can be thought of as a p-value).

**Comment by DrK-Lo** [comment]
Maybe someone else can post an example of how to start the Shiny server?

**Comment by grunwald** [comment]
To run the shiny R App do the following:

require(shiny)
require(devtools)
require(rCharts)
require(stats4)
require(scales)
# select the dir
setwd("~/.../MINOTAUR/inst")
runApp()
