### ISSUE TITLE
error with rCharts in latest version of R and MANIPULATE legacy

### ISSUE THREAD

**Issue by DrK-Lo** [NESCent/MINOTAUR#2]
Hi Team, I tried downloading our package from github but ran into some hurdles...

install.packages("devtools")
library(devtools)
install_github("NESCent/MINOTAUR")
library(MINOTAUR)

ERROR: dependencies ‘rCharts’, ‘rHighcharts’ are not available for package ‘MANIPULATE’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MANIPULATE’
Error: Command failed (1)
In addition: Warning message:
packages ‘rCharts’, ‘rHighcharts’ are not available (for R version 3.2.0)

**Comment by darencard** [comment]
Just tried it with R v. 3.1.3 (Smooth Sidewalk) and wasn't able to install MINOTAUR using devtools. Cloning and opening the package in R Studio worked fine for me though. Upgrading to R v. 3.2.0 right now (installing very slowly), as that might be the cause of the error you're getting.

**Comment by grunwald** [comment]
All runs fine for me downloading MINOTAUR fro github manually (e.g., not via devtools::...). I can run the shiny App. My question is what useful analysis can I currently do in the shiny app? 

The command line function like KernelDensity() run great!

Thanks,
Nik

> On May 9, 2015, at 7:44 AM, Daren Card <notifications@github.com> wrote:
> 
> Just tried it with R v. 3.1.3 (Smooth Sidewalk) and wasn't able to install MINOTAUR using devtools. Cloning and opening the package in R Studio worked fine for me though. Upgrading to R v. 3.2.0 right now (installing very slowly), as that might be the cause of the error you're getting.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/NESCent/MINOTAUR/issues/2#issuecomment-100498452>.
> 


Niklaus J. Grünwald
Research Plant Pathologist | Horticultural Crops Research Laboratory | USDA ARS
Professor (courtesy) | Department of Botany and Plant Pathology | Oregon State University
3420 NW Orchard Ave. | Corvallis, OR 97330 | USA | Tel 541.738-4049 | Fax 541.738-4025
grunwaldlab.cgrb.oregonstate.edu <http://grunwaldlab.cgrb.oregonstate.edu/> | phytophthora-id.org <http://phytophthora-id.org/> | oregonstate.edu/instruct/dce/phytophthora <http://oregonstate.edu/instruct/dce/phytophthora> | phytophthora-smallrna-db.cgrb.oregonstate.edu <http://phytophthora-smallrna-db.cgrb.oregonstate.edu/>

**Comment by darencard** [comment]
Shiny app worked fine for me with R v.3.2.0. Still not able to install via devtools, but I'm not too concerned about that right now.

Strangely, all of the packages I've previously installed are now missing upon the upgrade, including ones required by our app. I tried manually requiring some (e.g., adegenet), and got the anticipated error message saying that it isn't installed. However, the app still runs without issue. Not sure what's going on there. I was able to install rCharts and rHighCharts via devtools in this new version, so not sure where Katie's error is coming from.

**Comment by darencard** [comment]
... and currently I'm not sure there is much of anything useful you can do with the Shiny app. Some of the guts are there, such that if you can load a dataset you can subset and filter and probably make some plots, but not confident it would be that easy "out of the box".

**Comment by grunwald** [comment]
Thanks
