### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by darencard** [NESCent/MINOTAUR#7]
Looks like Bob's latest changes (last 2 commits) have led to some building errors that I'm observing on two computers. Checking out HEAD~3 (commit 693a0a2...) fixes the issue (my first experience doing this for real in git... I see the power!)

Error I'm getting appears to cite the functions Bob committed. Note that the warnings about replacing previous imports are not problem, they show up even when everything builds fine. Running R version 3.2.3 on Apple OSX 10.9.5. Here is full Build output:

```
==> Rcpp::compileAttributes()

* Updated src/RcppExports.cpp
* Updated R/RcppExports.R

==> R CMD INSTALL --no-multiarch --with-keep.source MINOTAUR

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’
* installing *source* package ‘MINOTAUR’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c harmonicDist.cpp -o harmonicDist.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o MINOTAUR.so RcppExports.o harmonicDist.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: replacing previous import by ‘fields::flame’ when loading ‘MINOTAUR’
Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘MINOTAUR’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: replacing previous import by ‘fields::flame’ when loading ‘MINOTAUR’
Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘MINOTAUR’
Error in namespaceExport(ns, exports) : 
  undefined exports: Mahalanobis, harmonicDist, kernelDist, kernelLogLike
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR’

Exited with status 1.
```

**Comment by bobverity** [comment]
OK,

It looks like I failed to add new files before committing last time. If you pull now you should see the new functions. Sorry!

Bob

On 17 Feb 2016, at 16:09, Daren Card <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like Bob's latest changes (last 2 commits) have led to some building errors that I'm observing on two computers. Checking out HEAD~3 (commit 693a0a2<https://github.com/NESCent/MINOTAUR/commit/693a0a2c38729bedba9518a9b7815d29d1a6bd22>...) fixes the issue (my first experience doing this for real in git... I see the power!)

Error I'm getting appears to cite the functions Bob committed. Note that the warnings about replacing previous imports are not problem, they show up even when everything builds fine. Running R version 3.2.3 on Apple OSX 10.9.5. Here is full Build output:

==> Rcpp::compileAttributes()

* Updated src/RcppExports.cpp
* Updated R/RcppExports.R

==> R CMD INSTALL --no-multiarch --with-keep.source MINOTAUR

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’
* installing *source* package ‘MINOTAUR’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c harmonicDist.cpp -o harmonicDist.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o MINOTAUR.so RcppExports.o harmonicDist.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: replacing previous import by ‘fields::flame’ when loading ‘MINOTAUR’
Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘MINOTAUR’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: replacing previous import by ‘fields::flame’ when loading ‘MINOTAUR’
Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘MINOTAUR’
Error in namespaceExport(ns, exports) :
  undefined exports: Mahalanobis, harmonicDist, kernelDist, kernelLogLike
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/MINOTAUR’

Exited with status 1.

**Comment by darencard** [comment]
Cool! That fixed it for me.
